### ISSUE TITLE
@s, @a, @p, @r, @e dont work

### ISSUE THREAD

**Issue by PotatoeTrainYT** [TuranicTeam/Altay#101]
#### Issue description

The @s, @a, @p, @r, @e in commands dont work
![screenshot 68](https://user-images.githubusercontent.com/30378179/40266596-3860932a-5b46-11e8-80a4-2a3b670de5f2.png)

#### Steps to reproduce the issue

Try using @s, @a, @p, @r, @e in a command

#### OS and versions

* Altay:1.2
* PHP:7.2
* Server OS:Windows
* Game version: 1.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by EmreTr1** [comment]
We implemented Command Selector feature but we dont add to all commands. Only some commands working with cmdselectors

**Comment by PotatoeTrainYT** [comment]
ah ok, are you planning on making it work, even for commands in plugins?

**Comment by EmreTr1** [comment]
Example: KillCommand

**Comment by EmreTr1** [comment]
Plugin Devs should write codes in Command

**Comment by EmreTr1** [comment]
like Example
