### ISSUE TITLE
Register Enchantment

### ISSUE THREAD

**Issue by xXNiceAssasinl0** [TuranicTeam/Altay#102]
How do I register a enchantment?

This doesn’t work 
self::registerEnchantment(new Enchantment(self::THORNS, "Thorns", self::RARITY_UNCOMMON, self::SLOT_ARMOR, 3));

**Comment by EmreTr1** [comment]
What is the 'self::' ?

**Comment by EmreTr1** [comment]
You should use 'Enchantment::'

**Comment by xXNiceAssasinl0** [comment]
I extends it @EmreTr1

**Comment by EmreTr1** [comment]
Have you any error in console

**Comment by xXNiceAssasinl0** [comment]
Yes but I forgot I’ll check in 10 mintues
