### ISSUE TITLE
Form sürekli yollanınca bozuluyor

### ISSUE THREAD

**Issue by bulutsun** [TuranicTeam/Altay#108]
Altay formlar oyuncuya ard arda gönderilince veya sohbet kutucugu acikken gonderilince form bozuluyor ve sunucudan cikis yapip tekrar girinceye kadar hiçbir altay form çalışmıyor. Konsolda hata yok.

* Altay: son sürüm
* PHP: 7.5
* Server OS: windows 10
* Game version: 1.4.0 windows 10

**Comment by EmreTr1** [comment]
Formlari ust ustemi aciyorsunuz yoksa birini kapatip digerinimi aciyorsunuz?

**Comment by bulutsun** [comment]
Mesela TPA davet formu oluşturdum. Kişi bunu oyuncuya sürekli olarak yolluyor ve bozuluyor. Yani üst üste yolluyor. Birde sohbet kutucuğu açıkken oyuncuya form gelince tamamen çöküyor altay form.

**Comment by EmreTr1** [comment]
Hmm anladim

**Comment by bulutsun** [comment]
Biraz daha ayrıntıya inmek gerekirse oyuncu sohbet kutucuğuna bir şey yazarken ve oyunu durdur menüsündeyken form yollayınca tüm altay form sistemi çöküyor oyuncunun çıkıp girmesi gerekiyor. Bu ileride çok büyük problemler yaratabilir. Benim sunucu projemide aksattı. En kısa zamanda çözersen çok sevinirim. İyi çalışmalar :)

**Comment by bulutsun** [comment]
Debug açınca olay sırasında bu yazılar geldi konsola; 

> 00:49:44 DEBUG > Got unexpected response for form 8, but waiting for response for
00:49:44 DEBUG > Unhandled ModalFormResponsePacket received from Steve: 0x65000008056e756c6c0a

**Comment by ErkamKahriman** [comment]
MInecraft hatasi olabilir

**Comment by bulutsun** [comment]
FormAPI'de böyle bir sıkıntı yok nedense

**Comment by EmreTr1** [comment]
Kodlari nasil yazdiniz acaba. Atma sansiniz varmi

**Comment by bulutsun** [comment]
Kodlar farketmiyor. Kendi kodlarimda hata vardir diye enesin shopmenusu uzerinden test yaptim ayni sorun devam ediyor.

**Comment by Enes5519** [comment]
Paket sorununu çözmeye vaktim olmadı. Müsait olduğum an ilgileneceğim
