### ISSUE TITLE
Windows 10 Edition bug

### ISSUE THREAD

**Issue by Crypt97** [TuranicTeam/Altay#109]
#### Issue description
The problem would be:

In Windows 10 Edition, there are many times that two-letter writers in chat or even more, and if you click on a shop's board, it detects more clicks than one.

Tested by phone and there is no problem with it!

Video: https://youtu.be/VIamWYiiqOg 

#### Steps to reproduce the issue
1. Open server
2. Join Server Windows 10 Edition and test (EssentialsShop,Join Message...etc.)

#### OS and versions

* Altay: 1.2
* PHP: 7.0 - 7.2
* Server OS: Windows 10
* Game version: Windows 10 Edition 1.4.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
-
```

**Comment by ErkamKahriman** [comment]
MC bug

**Comment by Crypt97** [comment]
And did anyone tell me to mojang? or do not you know?

**Comment by EmreTr1** [comment]
This a client bug. 
You can send a feedback to mojang : https://bugs.mojang.com/projects/MCPE/issues/MCPE-33999?filter=allopenissues
