### ISSUE TITLE
setCancelled() not working

### ISSUE THREAD

**Issue by Eren5960** [TuranicTeam/Altay#113]
setCancelled() not working in ProjectileEvent.

**Comment by EmreTr1** [comment]
Please describe the problem more understand and keep the issue template

**Comment by Eren5960** [comment]
Tmm boşver ingilizceyi.
Projectile Eventlerinde fonksiyonun içinde setCancelled kullanınca bir işe
yaramadı mı hata veriyor.

4 Haz 2018 Pzt 17:23 tarihinde Emre Yavuzyiğit <notifications@github.com>
şunu yazdı:
