### ISSUE TITLE
setCancelled() not working in Projectile Events

### ISSUE THREAD

**Issue by Eren5960** [TuranicTeam/Altay#114]
#### Issue description
ProjectileHitEvent içinde setCancelled () fonksiyonu çalışmıyor

#### OS and versions

* Altay: güncel
* PHP: 7.2.x 
* Server OS: CentOS
* Game version: 1.4.2

#### Crashdump, backtrace, memory dumps, plugins list or other files
Cloud not pass event setCancelled ()...

**Comment by Enes5519** [comment]
Altay sürümünüzü doğru giriniz. Ayrıca crashdump bölümüne ingilizce yazmışsınız. Bu bizim hatayı anlamamıza yardımcı olmaz.

**Comment by Eren5960** [comment]
Garip :-\ PrijectileHitEvent içinde setCancelled() çalışmıyor işte sıkıntı
bu yani en güncel Altay sürümü

5 Haz 2018 Sal 00:04 tarihinde Enes Yıldırım <notifications@github.com>
şunu yazdı:

**Comment by Enes5519** [comment]
Açık bir şekilde sorununuzu anlatamıyorsunuz. Kodlarınızı gönderebilir misiniz?

**Comment by Enes5519** [comment]
ProjectileHitEvent engellenemez.
