### ISSUE TITLE
Blockta Place Bug

### ISSUE THREAD

**Issue by Eren5960** [TuranicTeam/Altay#119]
#### Issue description
BLOCK KOYUNCA:
https://youtu.be/9jBgJKvV6bI
BLOCK Break:
Mcpe killed.

#### OS and versions

* Altay: 1.7
* PHP: 7.2.x
* Server OS: CentOS 7.x
* Game version: 1.4.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

Id 95 meta 9 does not have a corresponding BLOCK static runtime id, added a New unknown runtime id (4477)

**Comment by ErkamKahriman** [comment]
Is the map downloaded?

**Comment by Eren5960** [comment]
Yes

7 Haz 2018 Per 16:36 tarihinde Erkam Kahraman <notifications@github.com>
şunu yazdı:

**Comment by Eren5960** [comment]
Yes

**Comment by ErkamKahriman** [comment]
-.- then its normal

**Comment by Enes5519** [comment]
PC haritaları BE çevirince olur böyle. Runtime ID diye bir şey geldi bu yüzden tüm mapi fixlemen lazım.
