### ISSUE TITLE
CustomForm Çalışmıyor

### ISSUE THREAD

**Issue by Eren5960** [TuranicTeam/Altay#121]
#### Issue description
sendForm()  ile CustomForm sınıfını(yani CustomForm ekranı) çağırınca gelmiyor.

#### OS and versions

* Altay: 1.7
* PHP: 7.2.x
* Server OS: CentOS
* Game version: 1.4.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

Hata vermiyor.

**Comment by ErkamKahriman** [comment]
evet bende de ayni

**Comment by ErkamKahriman** [comment]
Tek MenuForm oluyor

**Comment by Eren5960** [comment]
Ee CustomForm ne zaman olucak?


7 Haz 2018 Per 21:53 tarihinde Erkam Kahraman <notifications@github.com>
şunu yazdı:

**Comment by Enes5519** [comment]
CustomForm gayet iyi çalışıyor.
