### ISSUE TITLE
Planting bug

### ISSUE THREAD

**Issue by Crypt97** [TuranicTeam/Altay#123]
#### Issue description
The problem is that plantations can not be trampled.

#### Steps to reproduce the issue
1. plant plant
2. jump on them

#### OS and versions

* Altay: 1.7
* PHP: 7.0 - 7.2
* Server OS: Windows 10
* Game version: Windows 10 Edition 1.4.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
-
```

**Comment by EmreTr1** [comment]
We need to implement Block::onFallenUpon function
