### ISSUE TITLE
Stone button and wood button bug

### ISSUE THREAD

**Issue by Crypt97** [TuranicTeam/Altay#124]
#### Issue description
When clicked, the button sticks and does not open the doors and anything.

#### Steps to reproduce the issue
1. place button
2. click button

#### OS and versions

* Altay: 1.7
* PHP: 7.0 - 7.2
* Server OS: Windows 10
* Game version: 1.4.2 Windows 10 Edition

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
-
```

**Comment by EmreTr1** [comment]
@Enes5519

**Comment by ErkamKahriman** [comment]
@Crypt97 why you create always issues and say its a bug this features are not implemented yet but redstone is in development

**Comment by Enes5519** [comment]
True

**Comment by Crypt97** [comment]
Because it used to be when it was not redstone.

**Comment by EmreTr1** [comment]
@Crypt97 thanks your interest. We will implement redstone but it is not stable now.
