### ISSUE TITLE
Server Start error

### ISSUE THREAD

**Issue by manyDARK** [TuranicTeam/Altay#134]
#### Issue description
Fatal error: Uncaught Error: Class 'pocketmine\snooze\SleeperHandler' not found in D:\TGC\Reload - TGC\src\pocketmine\Server.php:1496
Stack trace:
#0 D:\TGC\Reload - TGC\src\pocketmine\PocketMine.php(239): pocketmine\Server->__construct(Object(BaseClassLoader), Object(pocketmine\utils\MainLogger
#1 {main}
  thrown in D:\TGC\Reload - TGC\src\pocketmine\Server.php on line 1496

#### OS and versions
* Altay:
* PHP: 7.2.6
* Server OS: Windows Server 2012
* Game version: v1.4.0

**Comment by Enes5519** [comment]
You don't install composer or You don't update your composer.
