### ISSUE TITLE
Elytra da süzülürken havai fişek kullanınca havai fişek adeti azalmıyor

### ISSUE THREAD

**Issue by SuperAdam47** [TuranicTeam/Altay#137]
#### Issue description

Elytra da havai fişek kullanimi buglu
#### Steps to reproduce the issue
- elitrayı giydim
- elitraya yüksek bir yerden süzüldüm
- havadayken 12 fişeğimden çok fazla fişek kullandım ve adeti azalmadı

#### OS and versions

* Altay: 1.7
* PHP: 7.2
* Server OS: linux
* Game version: all

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Enes5519** [comment]
FOLLOW ISSUE TEMPLATE

**Comment by SuperAdam47** [comment]
anlamadın mı?
