### ISSUE TITLE
Armor Stand de item çoğaltma bugu

### ISSUE THREAD

**Issue by SuperAdam47** [TuranicTeam/Altay#138]
#### OS and versions

* Altay:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Enes5519** [comment]
Please send your plugins list and fill issue template. Because your issue closed

**Comment by SuperAdam47** [comment]
pluginlerle alakası olduğunu zannetmiyorum kendininzde deneyebilirsiniz
