### ISSUE TITLE
Iron Ore dont drop ingots

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [TuranicTeam/Altay#140]
GOLD, and Iron ores does not drop ingots,

Example:  https://github.com/TuranicTeam/Altay/blob/master/src/pocketmine/block/IronOre.php

**Comment by ErkamKahriman** [comment]
Iron ore doesn't drops ingots you need to use furnace...!!!

**Comment by TDMidkwhatisxd** [comment]
Awwww, forgot, fk im so stupid, and i even edited src to make sure it drops the ingots, ehhhh :)))))

P.S. i need to change my drugs :)))))
