### ISSUE TITLE
küçük hatalar

### ISSUE THREAD

**Issue by ejderoyundajb** [TuranicTeam/Altay#145]
- DoubleChest'i Açamama ( Zar Zor Açılıyor )
- Huni'yi Açamama

**Comment by EmreTr1** [comment]
Bende aciliyor?

**Comment by ejderoyundajb** [comment]
Play.HellCraftPe.Net gelip deneyebılırsın

**Comment by Eren5960** [comment]
Kullandığın bir eklenti ile çalışmış olabilir.

26 Haz 2018 Sal 19:58 tarihinde ResLio <notifications@github.com> şunu
yazdı:

**Comment by Eren5960** [comment]
Kullandığın eklentiler ile çalışıyor olabilir.

**Comment by Enes5519** [comment]
Eklentilerini kontrol etmeyi dene ve bir dahaki sefer issue template kullan.
