### ISSUE TITLE
Türkçe karakter sorunu

### ISSUE THREAD

**Issue by Eren5960** [TuranicTeam/Altay#146]
#### Issue description
Sohbet yerinde türkçe karaktere kadar olan harfleri gönderiyor

#### Steps to reproduce the issue
- Sohbeti açıYEAH
- "Selam Gençler" yazıYEAH
- Sohbete mesaj "Selam Gen" diye gidiYEAH

#### OS and versions
* Altay: En güncel
* PHP: 7.2.6
* Server OS: Linux
* Game version: 1.4.x-.1.5

#### Crashdump, backtrace, memory dumps, plugins list or other files

Hata yoh

**Comment by EmreTr1** [comment]
#blameMojang
