### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [TuranicTeam/Altay#147]
05:47:37 CRITICAL > InvalidArgumentException: "Value -1 exceeds the range!" (EXCEPTION) in "src/pocketmine/entity/Attribute" at line 191
05:47:37 DEBUG > #0 src/pocketmine/entity/Human(479): pocketmine\entity\Attribute->setValue(double -1)
05:47:37 DEBUG > #1 src/pocketmine/entity/Human(328): pocketmine\entity\Human->setXpAndProgress(integer -1, NULL )
05:47:37 DEBUG > #2 src/pocketmine/entity/Human(341): pocketmine\entity\Human->setXpLevel(integer -1)
05:47:37 DEBUG > #3 src/pocketmine/Player(2288): pocketmine\entity\Human->addXpLevels(integer -1)
05:47:37 DEBUG > #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(134): pocketmine\Player->handleEntityEvent(pocketmine\network\mcpe\protocol\EntityEventPacket object)
05:47:37 DEBUG > #5 src/pocketmine/network/mcpe/protocol/EntityEventPacket(106): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleEntityEvent(pocketmine\network\mcpe\protocol\EntityEventPacket object)
05:47:37 DEBUG > #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(94): pocketmine\network\mcpe\protocol\EntityEventPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
05:47:37 DEBUG > #7 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\EntityEventPacket object)
05:47:37 DEBUG > #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(94): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
05:47:37 DEBUG > #9 src/pocketmine/Player(3157): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
05:47:37 DEBUG > #10 src/pocketmine/network/mcpe/RakLibInterface(158): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
05:47:37 DEBUG > #11 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 68.237.134.91 55112, raklib\protocol\EncapsulatedPacket object, integer 0)
05:47:37 DEBUG > #12 src/pocketmine/network/mcpe/RakLibInterface(103): raklib\server\ServerHandler->handlePacket()
05:47:37 DEBUG > #13 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
05:47:37 DEBUG > #14 src/pocketmine/network/mcpe/RakLibInterface(80): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
05:47:37 DEBUG > #15 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
05:47:37 DEBUG > #16 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
05:47:37 DEBUG > #17 src/pocketmine/Server(2355): pocketmine\snooze\SleeperHandler->sleepUntil(double 1530251257.2759)
05:47:37 DEBUG > #18 src/pocketmine/Server(2265): pocketmine\Server->tickProcessor()
05:47:37 DEBUG > #19 src/pocketmine/Server(1829): pocketmine\Server->start()
05:47:37 DEBUG > #20 src/pocketmine/PocketMine(239): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/, string /root/plugins/)
05:47:37 DEBUG > #21 /root/PocketMine-MP.phar(1): require_once(string phar:///root/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by ErkamKahriman** [comment]
Follow issue template !

**Comment by ErkamKahriman** [comment]
And you cant add -1 xp levell..
