### ISSUE TITLE
/weather komutu yok

### ISSUE THREAD

**Issue by SuperAdam47** [TuranicTeam/Altay#149]
#### Issue description

/weather diye bir komut yok altayın son sürümünde.
#### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/16169771/42132781-3fe645ba-7d27-11e8-8f21-a361129f21cb.png)

#### OS and versions

* Altay: 1.7
* PHP: 7
* Server OS: windows
* Game version: 1.4.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Enes5519** [comment]
Hava durumu özelliği şuan da mevcut değil.

**Comment by SuperAdam47** [comment]
kapıyosan kapat invalid atma
🗡
