### ISSUE TITLE
Add stripped blocks

### ISSUE THREAD

**Issue by SuperAdam47** [TuranicTeam/Altay#150]
#### Issue description

- temiz bloklar eklenmeli altaya
- o bloklar altayda olmadığı için kendime givelediğim zaman başka itemler geliyor diamond, elma vb.
#### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/16169771/42132897-09ccb778-7d29-11e8-8669-39cb9ced15dd.png)

#### OS and versions

* Altay: 1.7
* PHP: 7
* Server OS: windows
* Game version: 1.4.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Enes5519** [comment]
Başka bir eşya gelme şansı yoktur o liste vanilla minecraft'daki liste ve böyle kalması daha mantıklı her blok ekleyişimiz de orayı değiştiremeyiz

**Comment by SuperAdam47** [comment]
senin yorumun Invalid
