### ISSUE TITLE
Altay Hacke açık

### ISSUE THREAD

**Issue by SuperAdam47** [TuranicTeam/Altay#151]
#### Issue description

Altayda op Hack kullanılıyor adam sunucuma girip gamemode fln değiştirdi altay kullanmayın pmmp kullanın dedi.
#### OS and versions

* Altay:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by SuperAdam47** [comment]
@EmreTr1 @Enes5519 @Prisane @krglata @Palente PRİOTRY HİGH!

DANGER!!

**Comment by ErkamKahriman** [comment]
Ne alaka

**Comment by ErkamKahriman** [comment]
Olamazki

**Comment by SuperAdam47** [comment]
kendim yazdım diyo adam programı javayla

**Comment by SuperAdam47** [comment]
@Enes5519 alican çopurla konuşmalısın bu biliyor op hackini yardımı dokunabilir.

**Comment by Enes5519** [comment]
Benim sunucumda engelleme yaptım.

**Comment by ferhatbostanci** [comment]
@Enes5519  Paylaşta bizde engelleyelim 👍

**Comment by Enes5519** [comment]
Op hacki diye bir şey olmaz. Proxy olur ona da detaylı bir Anti Hack yapman lazım. Ben popüler proxyleri sunucumda engelledim ama localde çalışanlar için detaylı bir çalışma yapmak gerekir ona da başlamadım ve paylaşamam.

**Comment by ferhatbostanci** [comment]
@Enes5519 Peki OP hack ile yapilacaklar nelerdir aciklarsan bizde önlem alalım.

**Comment by Enes5519** [comment]
OP hack diye bir şey imkansız. OP paketler ile verilmiyor çünkü proxy olsa bile yapamaz.

**Comment by ferhatbostanci** [comment]
@Enes5519 Soruyu yanlış sordum o zaman, bu açık ile mesela neler yapılabilir GM değiştiriyorum dediye give komutu vs kullanılabilirmi onu soruyorum :)

**Comment by Enes5519** [comment]
Sanırım okumuyorsunuz Ferhat bey lütfen okuyunuz anlayacaksınız + Gamemode normal launcherlar ile de değiştirilebilir

**Comment by SuperAdam47** [comment]
![36779225_849810508547065_6244575396877041664_n](https://user-images.githubusercontent.com/16169771/42422706-f04710ac-82f3-11e8-999a-d36bcb997017.jpg)
fix pls src içini değiştirmeye çalışıp uğraşmayalım

**Comment by SuperAdam47** [comment]
@Enes5519

**Comment by Enes5519** [comment]
Ben şayet kendi sunucuma davet edip denettirdim. Hiç bir ek ayar olmamasına karşın yaptığı şeyin işe yaramadığını söyledi bu konuda size yardımcı olamayacağım.
