### ISSUE TITLE
İtem çoğaltma bugu

### ISSUE THREAD

**Issue by SuperAdam47** [TuranicTeam/Altay#158]
#### Issue description

- https://youtu.be/HoanB_r2qaY
- Videoda gördüğünüz gibi itemleri armor standda yağma büyülü bir kılıçla çoğaltabiliyoruz
#### OS and versions

* Altay: 1.7
* PHP: 7.2
* Server OS: Linux
* Game version: 1.4.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Enes5519** [comment]
Altay'da yağma büyüsü yok ki.

**Comment by Enes5519** [comment]
Sanırım sen **VanillaEnchantments** kullanıyorsun bu onların issue'si.
