### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SuperAdam47** [TuranicTeam/Altay#159]
#### Issue description

![image](https://user-images.githubusercontent.com/16169771/42471044-0cc3e3f0-83c5-11e8-942e-206f73175eac.png)

#### OS and versions

* Altay: 1.7
* PHP: 7.2
* Server OS: Linux
* Game version: 1.4.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by EmreTr1** [comment]
@Enes5519

**Comment by Enes5519** [comment]
Altay 1.7 sürümü artık çok eski yeni sürüm kullanmanızı öneririm.

**Comment by SuperAdam47** [comment]
Deneyeceğim
