### ISSUE TITLE
Hazır harita sorunu

### ISSUE THREAD

**Issue by Eren5960** [TuranicTeam/Altay#162]
#### Issue description
Hazır haritalara gidince oyun çöküyor.

#### Steps to reproduce the issue
Default haritayı hazır map yapınca da çöküyor, TP ile de çöküyor

#### OS and versions

* Altay: 3.0.7
* PHP: 7.2.6
* Server OS: Linux
* Game version: 1.5

#### Crashdump, backtrace, memory dumps, plugins list or other files

 Hata yok

**Comment by Enes5519** [comment]
Hazır haritalarda değil sıkıntı entity paketlerinde sıkıntı var.
