### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xkhhv** [TuranicTeam/Altay#166]
14:35:46 CRITICAL > Error: "Class 'pocketmine\network\mcpe\protocol\MoveEntityAbsolutePacket' not found" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/PacketPool" at line 51
14:35:46 DEBUG > #0 src/pocketmine/network/Network(55): pocketmine\network\mcpe\protocol\PacketPool::init()
14:35:46 DEBUG > #1 src/pocketmine/Server(1674): pocketmine\network\Network->__construct(pocketmine\Server object)
14:35:46 DEBUG > #2 src/pocketmine/PocketMine(241): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\khale\Desktop\PocketMine-MP\, string C:\Users\khale\Desktop\PocketMine-MP\plugins\)
14:35:46 EMERGENCY > An unrecoverable error has occurred and the server has crashed. Creating a crash dump
14:35:46 EMERGENCY > Please upload the "C:\Users\khale\Desktop\PocketMine-MP\crashdumps/Fri_Jul_13-14.35.46-EAT_2018.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
bin\php\php.exe: Exit 1

**Comment by Eren5960** [comment]
Wait for update

**Comment by Enes5519** [comment]
You reinstall Altay

**Comment by xkhhv** [comment]
How?

**Comment by ErkamKahriman** [comment]
like a boss

**Comment by xkhhv** [comment]
Hhh, you are funny
