### ISSUE TITLE
Versiyon hatası

### ISSUE THREAD

**Issue by SeymennC** [TuranicTeam/Altay#170]
#### Issue description

Versiyon sorunu

#### Steps to reproduce the issue

MCPE sürümü 1.4den girince istemci sürümü güncel değil diyor ama 1.5den girilmeye çalışınca da dünyaya bağlanılamıyor diyor. 
#### OS and versions

* Altay: 3.0.4+dev
* PHP: 7.2
* Server OS: Linux
* Game version: 1.5.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```

```

**Comment by EmreTr1** [comment]
1.4 ten girince guncel dememesi normal cunku sunucu 1.5 .d, dunyaya baglanilamiyir harasi cihazinla akakali olabilirmi?

**Comment by Enes5519** [comment]
Bu sorun şöyle anlatayım:
- Kullandığın mcpe orjinal olmayabilir. Yeniden indirmeyi dene.
- 1.5'de arada banada oluyor ama bende şöylle oluyor sunucu açılırken girersem oluyor. Sunucu yazısını görünce girmeyi dene
- Bu bug Altay ile ilgili değil Mojang ile alakalı
