### ISSUE TITLE
World Teleport Bug

### ISSUE THREAD

**Issue by TobiasDevDE** [TuranicTeam/Altay#176]
#### Issue description
When trying to teleport a Player to some coords at a specified world

#### Steps to reproduce the issue
teleport Player with $player->teleport($x, $y, $z, $world);

#### OS and versions

* Altay: 3.0.6-dev
* PHP: 7.2
* Server OS: Debian 8 64 Bit
* Game version: 1.5

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ErkamKahriman** [comment]
@TobiasDevDE 
And you know you cant teleport player in other world with this code $player->teleport($x, $y, $z, $world);
You need to use Position

**Comment by TobiasDevDE** [comment]
Oh ok, error is a binary stream error, I'll try with positions

**Comment by EmreTr1** [comment]
and you should load world before @TobiasDevDE
