### ISSUE TITLE
Report gegen Amboss

### ISSUE THREAD

**Issue by DerGamerHD100** [TuranicTeam/Altay#180]
Guten Tag

Liebes TuranicTeam/Altay-Team
Man kann wenn man im Amboss ist und ein Item rein macht man das Item unbenannt hat und man es mit rechtsklick das raus nehmen möchte Dupliziert sich das Item! Bitte Beheben danke :D

Mit freundlichen grüßen DerGamerHD100

**Comment by ErkamKahriman** [comment]
Das ist schon bekannt..

**Comment by DerGamerHD100** [comment]
Wir das gefixt?

**Comment by ErkamKahriman** [comment]
kp

**Comment by DerGamerHD100** [comment]
Ok und wie kann ich amboss deaktivieren? wäre das möglich

**Comment by ErkamKahriman** [comment]
InteractEvent

**Comment by DerGamerHD100** [comment]
Danke lol

**Comment by DerGamerHD100** [comment]
Dauert es noch lange bis es gefixt wird?

**Comment by Enes5519** [comment]
You must write in English
