### ISSUE TITLE
Entity not update nametag when set

### ISSUE THREAD

**Issue by TanToan99** [TuranicTeam/Altay#181]
#### Issue description
Setnametag but Entity not update

#### Steps to reproduce the issue
1. Install slapper plugins
2. /slapper create Player AAA 
example id : 1
We will see slapper with name AAA
3. /slapper edit 1 name BBB
Name slapper not update 
4. stop and start server again we will see name is BBB
please fix it 

I try to use `$entity->setNameTag("new name")` but not working too !

#### OS and versions

OS and versions
* Altay: 3.0.7+dev
* PHP: 7.2.0
* Server OS: windows10
* Game version: 1.5.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by EmreTr1** [comment]
plugin issue
