### ISSUE TITLE
translate bug eng.ini

### ISSUE THREAD

**Issue by NikeboyHU** [TuranicTeam/Altay#25]
#### Issue description
translate bug in language .ini files or any configuration.
ex.: "{0%} joined the game"

#### OS and versions

* Altay: latest
* PHP: 7.2
* Server OS: Ubuntu Linux
* Game version: 1.2.9

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Enes5519** [comment]
![eng.ini](http://i.hizliresim.com/LbZQ7b.png)
