### ISSUE TITLE
raklib error, and sometimes crash

### ISSUE THREAD

**Issue by NikeboyHU** [TuranicTeam/Altay#26]
#### Issue description
raklib error and sometimes crashing, and closing raklib (raknet thread interface crash)

#### OS and versions

* Altay: latest
* PHP: 7.2
* Server OS: Ubuntu Linux (with Multicraft)
* Game version: 1.2.9

#### Crashdump, backtrace, memory dumps, plugins list or other files
raklib error file with debug: 
[Raklib_Error.txt](https://github.com/TuranicTeam/Altay/files/1704213/Raklib_Error.txt)
```
```

**Comment by NikeboyHU** [comment]
Packet debug error:
08.02 16:06:18 [Server] DEBUG  Received garbage message from 50.107.92.239 19132 (Packet magic is invalid): 01303066666666303066656665666566656664666466646664313233343536373800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
08.02 16:06:18 [Server] DEBUG  #0 /vendor/pocketmine/raklib/server/SessionManager(135): raklib\server\SessionManager->receivePacket()
08.02 16:06:18 [Server] DEBUG  #1 /vendor/pocketmine/raklib/server/SessionManager(127): raklib\server\SessionManager->tickProcessor()
08.02 16:06:18 [Server] DEBUG  #2 /vendor/pocketmine/raklib/server/SessionManager(103): raklib\server\SessionManager->run()
08.02 16:06:18 [Server] DEBUG  #3 /vendor/pocketmine/raklib/server/RakLibServer(220): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object, integer 1492)
08.02 16:06:18 [Server] DEBUG  #4 (): raklib\server\RakLibServer->run()
08.02 16:06:18 [Server] NOTICE  Blocked 50.107.92.239 for 5 seconds

**Comment by NikeboyHU** [comment]
And raklib crash reproduced, when inventory opened. 
Raklib error with debug below:
[Raklib_Error.txt](https://github.com/TuranicTeam/Altay/files/1707573/Raklib_Error.txt)

**Comment by Crypt97** [comment]
Nem lehet hogy valami plugin miatt ilyen?

**Comment by EmreTr1** [comment]
are you using another mpe launcher(blocklauncher, mcpemaster etc.) ?

**Comment by Enes5519** [comment]
@EmreTr1 Bu windows 10 editionda çarpıdan kapatınca hatra çıkıyor sanırım o hata emin olamadığım için kapatmadım

**Comment by ErkamKahriman** [comment]
Is this problem still there?
