### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Crypt97** [TuranicTeam/Altay#27]
Where are php 7.2.0 RC3 for Windows 64 bit?

**Comment by keke1229488344** [comment]
I also want to know how to find php7.2.0 RC3 .

**Comment by keke1229488344** [comment]
I'm Chinese.Would you like to make friends with me?My QQ number:1229488344

**Comment by Crypt97** [comment]
Wok!!!! https://seattle.github.com/shoki-3738/pmmp-Binary
