### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shdudwns** [TuranicTeam/Altay#3]
07:40:15 CRITICAL > Error: "Class 'pocketmine\item\Elytra' not found" (EXCEPTION) in "src/pocketmine/item/ItemFactory" at line 226
07:40:15 DEBUG > #0 src/pocketmine/Server(1673): pocketmine\item\ItemFactory::init()
07:40:15 DEBUG > #1 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /mnt/c/Users/.../pm/, string /mnt/c/Users/.../pm/plugins/)
07:40:15 EMERGENCY > An unrecoverable error has occurred and the server has crashed. Creating a crash dump
07:40:16 EMERGENCY > Please upload the "/mnt/c/Users/준/pm/crashdumps/Thu_Feb_1-07.40.15-UTC_2018.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by Enes5519** [comment]
This is impossible
