### ISSUE TITLE
CustomForm error

### ISSUE THREAD

**Issue by KenMizz** [TuranicTeam/Altay#30]
#### Issue description

CustomForm error
#### Steps to reproduce the issue

create a customForm
run
#### OS and versions

* Altay:2989bc1
* PHP:7.2
* Server OS:Windows 10
* Game version: 1.2.10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Cannot instantiate abstract class pocketmine\form\CustomForm
```

**Comment by ErkamKahriman** [comment]
Send code

**Comment by Enes5519** [comment]
This is not issue. You just do not know how to use it. Example:
```
Player->sendForm(
    new class("title", []) extends CustomForm{

    }
);
