### ISSUE TITLE
Armor stands bug

### ISSUE THREAD

**Issue by SuperKali** [TuranicTeam/Altay#33]
#### Issue description

https://youtu.be/DSNR3C-DOvM
#### OS and versions

* Altay: 
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ErkamKahriman** [comment]
Armorstand is not added its in another branch

**Comment by SuperKali** [comment]
@ErkamKahriman  yes i tested the other branch but is private for all collaborators

**Comment by DevColdSpeed** [comment]
Good Job Ya'll
