### ISSUE TITLE
Phar

### ISSUE THREAD

**Issue by poustmal** [TuranicTeam/Altay#4]
Phar link?

**Comment by AhmetAyn** [comment]
Phar Link?

**Comment by NikeboyHU** [comment]
Download zip, unzip files, and start server in any folder with start*.cmd file. If server started, use cmd "ms" and wait for generating software file.

**Comment by poustmal** [comment]
Im using my phone to make phar so i cant do that

**Comment by kaliiks** [comment]
Then you can't
