### ISSUE TITLE
When player/console change gamemode, it will not  correct display.

### ISSUE THREAD

**Issue by Tommy131** [TuranicTeam/Altay#41]
#### Issue description
When player/console change gamemode, it will not  correct display.

#### Steps to reproduce the issue
when console send command "gm 1|0 <player_name>", console will get a correct Gamemode change display, but player cannot get a correct Gamemode change display.
and when player send the same as command "gm 1|0", player will get a correct Gamemode change display, but console cannot get a correct Gamemode change display.

#### OS and versions

* Altay: Turanic 1.2.9 (i modified protocol to 201)
* PHP: 7.0.17
* Server OS: Windows 10
* Game version: 1.2.10

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
NULL
```

**Comment by ErkamKahriman** [comment]
Use the newest version you use a modified version

**Comment by ErkamKahriman** [comment]
http://turanic.io:8181/

**Comment by VoltexYT** [comment]
🗡

**Comment by Tommy131** [comment]
but this version change a lot... for example Task and Command
