### ISSUE TITLE
Update new CompoundTag and more nbt

### ISSUE THREAD

**Issue by SuperKali** [TuranicTeam/Altay#43]
#### Issue description

hi, @Enes5519 i request the update nbt tags and more codes because PureEntities not work with this version and with the last version of pmmp work.

#### OS and versions

* Altay: https://github.com/TuranicTeam/Altay/commit/4a3d29f4337451d0d11b7870f376e9bb13734204
* PHP: 7.2
* Server OS: Linux (Debian 9.2)
* Game version: W10 Edition

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ErkamKahriman** [comment]
It won't work cause we changed the api and it will not work with it.
