### ISSUE TITLE
Please, add a Painting to inventory and level

### ISSUE THREAD

**Issue by ProCOmpTEAM** [TuranicTeam/Altay#44]
#### Steps to reproduce the issue

if i try to set block Painting then it is'nt create

#### OS and versions

* Altay: "TuranicPro" (API 3.0.1) : latest build
* PHP: 7.2
* Server OS: windows 10 / linux mint mate 17
* Game version: 1.2.10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ErkamKahriman** [comment]
Level? is already added...

**Comment by ProCOmpTEAM** [comment]
@ErkamKahriman to level*, sorry

**Comment by ProCOmpTEAM** [comment]
@ErkamKahriman to level*, sorry

**Comment by ErkamKahriman** [comment]
?

**Comment by ProCOmpTEAM** [comment]
@ErkamKahriman Painting is not exists in inventory and this block in level can'nt place

**Comment by ErkamKahriman** [comment]
oh ok

**Comment by ProCOmpTEAM** [comment]
@ErkamKahriman what news?

**Comment by ProCOmpTEAM** [comment]
@Enes5519 please, add this, i have rp server and i really need for it
