### ISSUE TITLE
Item droping

### ISSUE THREAD

**Issue by Jonathanftw** [TuranicTeam/Altay#56]
When you try dropping any items and on death they do not drop their items

**Comment by Enes5519** [comment]
You use old version.

**Comment by Enes5519** [comment]
FOLLOW ISSUE TEMPLATE

**Comment by MalakasPlayzMC** [comment]
Because I have some questions and I don't want to open a useless issue, is this for PHP7, 32-bit devices and 1.2.10?

**Comment by Enes5519** [comment]
No
