### ISSUE TITLE
Need Pocketmine-MP.phar!

### ISSUE THREAD

**Issue by HonorGamerHD** [TuranicTeam/Altay#58]
#### Issue description
Hey, i need the Pocketmine-MP.phar the run the Server software.

#### Steps to reproduce the issue
Can you send me the phar file, please?

#### OS and versions

* Altay:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ErkamKahriman** [comment]
http://turanic.io
