### ISSUE TITLE
Water Bar, World No load, Glitchin Spawning!

### ISSUE THREAD

**Issue by DevCold967** [TuranicTeam/Altay#61]
#### Issue description
When I spawn in-to my "Genysis" World, with your software, there is no world load, Water bar is out even thought not in water at all!, & when spawning, your game is glitchey

#### Steps to reproduce the issue
Fix the problem

#### OS and versions

* Altay:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by DevCold967** [comment]
Why?

**Comment by DevCold967** [comment]
No, 64

**Comment by EmreTr1** [comment]
do you using android phone

**Comment by DevCold967** [comment]
Nope,

**Comment by DevCold967** [comment]
And don't copy other peoplez, work

**Comment by Enes5519** [comment]
Please follow issue template @DevCold967
