### ISSUE TITLE
Spam on console

### ISSUE THREAD

**Issue by Fr3llyOfficial** [TuranicTeam/Altay#67]
#### Issue description

why write this on the console?
NOTICE > Blocked 45.79.134.18 for 5 seconds
#### OS and versions

* Altay: 3e36c3c
* PHP: 7.2
* Server OS: Ubuntu 16.04.4 LTS 
* Game version: 1.2.11

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Fr3llyOfficial** [comment]
this is it?
(http://turanic.io:8181/job/Altay/95/console)

**Comment by ErkamKahriman** [comment]
If you use .phar you don't need composer..

**Comment by ErkamKahriman** [comment]
Can you send the error above `xx.xx.xxx.xx` blocked?

**Comment by Fr3llyOfficial** [comment]
does not write an error.

**Comment by Fr3llyOfficial** [comment]
I have pocketmine-mp, how to install composer?

**Comment by ErkamKahriman** [comment]
If you install pmmp why you create a issue here?
