### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by majo55** [TuranicTeam/Altay#68]
Hello, sorry i not create template but i have only one question why we not you aktuali pmmp api ?

**Comment by Enes5519** [comment]
what means "aktuali" ?

**Comment by majo55** [comment]
current

**Comment by Enes5519** [comment]
The difference is our style. IDK

**Comment by majo55** [comment]
i have pets plugin and me work on pmmp and on altay crashed

**Comment by Enes5519** [comment]
You don't use last pmmp.

**Comment by majo55** [comment]
i use lates version from jenkins

**Comment by Enes5519** [comment]
if you come to our discord channel, you can tell me more about it.
