### ISSUE TITLE
 Composer autoloader not found.

### ISSUE THREAD

**Issue by mashabear** [TuranicTeam/Altay#7]
####을 발행하다. 설명
<!..-그 문제에 대해 간단히 설명하다-->.
 Composer autoloader not found.

####단계로 번식하다.
<!..-우리에게 단계로 문제가 번식에 추가하여는 문제를 찾아내도록 도와 주세요-->.
 Composer autoloader not found.
####OS와 버전
<!..-
유효한 버전,"최근"이 무효하다는 것을 짓는 번호나git 해시가 포함되어야 합니다.
만약 버전이 잘못되었으면 문제 문 닫음 것이다.
게임 버전 암반 엔진, Windows10에디션 버전을 포함한다.
-->
*알타이:
*PHP: 7.2.1
*서버 OS: linux Ubuntu Server 16.04
*게임 버전: 1.2.X

####Crashdump, backtrace, 메모리 덤프, 플러그 인 목록 또는 기타 파일을.
<아래 블록에!..-반죽은-->.
"`[CRITICAL] Composer autoloader not found.
[CRITICAL] Please install/update Composer dependencies or use provided builds.
anode24@ubuntu:~/ras$ ./starts.sh
[CRITICAL] Composer autoloader not found.
[CRITICAL] Please install/update Composer dependencies or use provided builds.
anode24@ubuntu:~/ras$

[ERROR] Couldn't find a valid Altay installation.

"`

**Comment by Enes5519** [comment]
I add wiki for composer install. Also this is not issue. Please don't spam.
