### ISSUE TITLE
PLEASE RESOLV THIS WITH ENTITY

### ISSUE THREAD

**Issue by dennisslol006** [TuranicTeam/Altay#74]
14:16:33 CRITICAL > RuntimeException: "Expected a tag of type pocketmine\nbt\tag\ShortTag, got pocketmine\nbt\tag\IntTag" (EXCEPTION) in "vendor/pocketmine/nbt/src/tag/CompoundTag" at line 107
14:16:33 DEBUG > #0 vendor/pocketmine/nbt/src/tag/CompoundTag(309): pocketmine\nbt\tag\CompoundTag->getTag(string EntityId, string pocketmine\nbt\tag\ShortTag)
14:16:33 DEBUG > #1 vendor/pocketmine/nbt/src/tag/CompoundTag(336): pocketmine\nbt\tag\CompoundTag->setTagValue(string EntityId, string pocketmine\nbt\tag\ShortTag, integer 11, boolean )
14:16:33 DEBUG > #2 PureEntities by Denniss/src/milk/pureentities/tile/Spawner(100): pocketmine\nbt\tag\CompoundTag->setShort(string EntityId, integer 11)
14:16:33 DEBUG > #3 src/pocketmine/level/format/io/region/Anvil(79): milk\pureentities\tile\Spawner->saveNBT()
14:16:33 DEBUG > #4 src/pocketmine/level/format/io/region/McRegion(375): pocketmine\level\format\io\region\Anvil->nbtSerialize(pocketmine\level\format\Chunk object)
14:16:33 DEBUG > #5 src/pocketmine/level/format/io/BaseLevelProvider(133): pocketmine\level\format\io\region\McRegion->writeChunk(pocketmine\level\format\Chunk object)
14:16:33 DEBUG > #6 src/pocketmine/level/Level(2801): pocketmine\level\format\io\BaseLevelProvider->saveChunk(pocketmine\level\format\Chunk object)
14:16:33 DEBUG > #7 src/pocketmine/level/Level(442): pocketmine\level\Level->unloadChunk(integer 26, integer 14, boolean )
14:16:33 DEBUG > #8 src/pocketmine/level/Level(578): pocketmine\level\Level->close()
14:16:33 DEBUG > #9 src/pocketmine/Server(1009): pocketmine\level\Level->unload(boolean 1)
14:16:33 DEBUG > #10 src/pocketmine/Server(2091): pocketmine\Server->unloadLevel(pocketmine\level\Level object, boolean 1)
14:16:33 DEBUG > #11 src/pocketmine/Server(2283): pocketmine\Server->forceShutdown()
14:16:33 DEBUG > #12 src/pocketmine/Server(2218): pocketmine\Server->crashDump()
14:16:33 DEBUG > #13 src/pocketmine/Server(1761): pocketmine\Server->exceptionHandler(RuntimeException object)
14:16:33 DEBUG > #14 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Denniss\Desktop\PocketMine-MP\, string C:\Users\Denniss\Desktop\PocketMine-MP\plugins\)
14:16:33 DEBUG > #15 C:/Users/Denniss/Desktop/PocketMine-MP/PocketMine-MP.phar(1): require_once(string phar://C:/Users/Denniss/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by Enes5519** [comment]
FOLLOW ISSUE TEMPLATE!!!!
