### ISSUE TITLE
armor & elytra bug & head

### ISSUE THREAD

**Issue by Fr3llyOfficial** [TuranicTeam/Altay#77]
#### Issue description

https://youtu.be/miORxpPC02E
#### Steps to reproduce the issue

please fix it.
#### OS and versions

* Altay: fa31f70
* PHP: 7.2
* Server OS: Ubuntu 16.04
* Game version: 1.2.11

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ErkamKahriman** [comment]
Use /gm 0
and there are no problems

**Comment by Fr3llyOfficial** [comment]
okay :/
Thanks.

**Comment by shdudwns** [comment]
And /clear

**Comment by Enes5519** [comment]
You're just cleaning up the inventory. You should clean up your armor inventory.
