### ISSUE TITLE
Some bugs!!

### ISSUE THREAD

**Issue by OtorisanVardo** [TuranicTeam/Altay#78]
#### Issue description

When player touches some block on ground, these blocks appear like cross.
![img](https://i.imgur.com/wfrGO6I.png)
(Look at picture)

And, player's bubble is displayed.
(Look at picture)
  
#### Steps to reproduce the issue

Join, and Touch

#### OS and versions
use Win10

* Altay: Latest commit version
* PHP: latest (7)
* Server OS: Win10
* Game version: 1.12.11

#### Crashdump, backtrace, memory dumps, plugins list or other files

None

**Comment by OtorisanVardo** [comment]
And now, we can't place blocks...

**Comment by ErkamKahriman** [comment]
Use newest version!
