### ISSUE TITLE
Ran out of memory and freeze server random times

### ISSUE THREAD

**Issue by NikeboyHU** [TuranicTeam/Altay#8]
#### Issue description
Memory reach 2048 MB allowed memory and freeze server, but it varies from time to time after restarting even a few minutes or after 1-2 days

async-compression is disabled!

no error, no debug, nothing.

#### OS and versions

* Altay: latest
* PHP: 7.2
* Server OS: Ubuntu Linux 18.04
* Game version: 1.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ErkamKahriman** [comment]
Then you need more ram

**Comment by ErkamKahriman** [comment]
Try PocketMine i think you will have the same problem there

**Comment by NikeboyHU** [comment]
1-2 days it's okay, but same minutes after startup?

**Comment by NikeboyHU** [comment]
@ErkamKahriman 
I found the error probable. Does the dragon egg work properly?

**Comment by Heroata** [comment]
Before create a new issue, please debug it. There is no info about what's going on in your server. So we can't comment about it. Maybe only a plugin causing it. But if you found a bug or critical error about Altay, come and report it pls. Btw you're talking about 1-2 days. Its only 2 days repo. So you are using Turanic. This is not Turanic repo but Altay.
