### ISSUE TITLE
Incompatible API version

### ISSUE THREAD

**Issue by Franklau1212** [TuranicTeam/Altay#83]
#### Issue description
Altay cannot support api which is below 3.0

#### Steps to reproduce the issue
1.Start the server correctly
2.Put my plugins which are under api 3.0
3.It says api is not support.

#### OS and versions
OS Centos 6.9 Final
Version Minecraft 1.2.13 (latest)
* Altay: Yes (latest)
* PHP: 7.2
* Server OS:CentOS 6.9 Final
* Game version: 1.2.13

#### Crashdump, backtrace, memory dumps, plugins list or other files

Could not load plugin 'duoshijie': Incompatible API version

**Comment by Enes5519** [comment]
https://github.com/TuranicTeam/Altay/blob/master/src/pocketmine/resources/altay.yml#L22 is true ?
