### ISSUE TITLE
Maden Craftlama

### ISSUE THREAD

**Issue by ejderoyundajb** [TuranicTeam/Altay#86]
Maden Craftlıyınca Hata Verıyor ? ve sunucu çöküyor ancak reboot atınca tekrar devam edebılıyorum
1.2.13 eşyaları ile altaydaki eşyalar uyumlu değil sanırım çökme yaşanıp duruyor özellikle madenler craftlayınca

**Comment by ErkamKahriman** [comment]
yeni version da fixlendi aslinda...

**Comment by ejderoyundajb** [comment]
ben bildirmiştim tekrar fakat son sürümü kullanıyorum aynısı tekrar oldu

**Comment by ejderoyundajb** [comment]
madenleri craftta dönüştürünce sunucu çöküyor anlamsız ca

**Comment by EmreTr1** [comment]
hangi maden blokları? @ejderoyundajb

**Comment by Enes5519** [comment]
Lütfen verdiğimiz issue şablonunu kullanınız aksi takdirde sorununuza çözüm bulamayız. İyi günler.
