### ISSUE TITLE
I don't know why I can't use new Altay on PHP7.2(RC3),but I can use the mcpe-v1.2.10

### ISSUE THREAD

**Issue by bzdnd** [TuranicTeam/Altay#88]
[ERROR] Altay requires PHP >= 7.2.0, but you have PHP 7.2.0RC3
-------------------------So I can't use it on PHO7.2RC3?(the core support mcpe 1.2.13)
--------------------------but I can use the older Altay on the PHP7.2RC3(the core support mcpe1.2.10)
17.04 20:50:39 [服务器] 信息 12:50:39 信息 > 加载完成 (2.363 秒)！如需帮助，请键入 "help" 或 "?"
17.04 20:50:39 [服务器] 信息 12:50:39 信息 > 默认游戏模式：生存模式
17.04 20:50:39 [服务器] 信息 12:50:39 信息 > Query 正在运行于 0.0.0.0:55720
17.04 20:50:39 [服务器] 信息 12:50:39 信息 > 正在设置 query 端口到 55720
17.04 20:50:37 [服务器] 信息 12:50:37 信息 > Loading resource packs...
17.04 20:50:37 [服务器] 信息 12:50:37 信息 > Loading recipes...
17.04 20:50:37 [服务器] 信息 12:50:37 信息 > Altay 依照LGPL协议分发
17.04 20:50:37 [服务器] 信息 12:50:37 信息 > 此服务器正在运行 Altay 版本 1.2 "TuranicPro" (API 3.0.1)
17.04 20:50:37 [服务器] 信息 12:50:37 信息 > 正在启动服务器于 0.0.0.0：55720
17.04 20:50:37 [服务器] 信息 12:50:37 WARNING > To enable authentication, set "xbox-auth" to "true" in server.properties.
17.04 20:50:37 [服务器] 信息 12:50:37 WARNING > While this makes it possible to connect without internet access, it also allows hackers to connect with any username they choose.
17.04 20:50:37 [服务器] 信息 12:50:37 WARNING > Online mode is disabled. The server will not verify that players are authenticated to Xbox Live.
17.04 20:50:37 [服务器] 信息 12:50:37 信息 > 正在启动 Minecraft: PE 服务器，版本号：v1.2.10

**Comment by ErkamKahriman** [comment]
You need a newer binarys version and follow issue template!
