### ISSUE TITLE
What's happening?

### ISSUE THREAD

**Issue by OtorisanVardo** [TuranicTeam/Altay#93]
#### Issue description

Load level forever

#### Steps to reproduce the issue

use function "teleport()" 
Forever my screen become like the image.
![Imgur](https://i.imgur.com/5IC6k6Q.jpg)
#### OS and versions

* Altay: ae90d6cc39bc26a92621db1886ddef3d7529d125
* PHP: 7.0.2
* Server OS: linux
* Game version:  1.2.13

**Comment by Enes5519** [comment]
Oh. I understand. Because of level dimensions. Also Altay PHP version is 7.2 but you use 7.0.2.
