### ISSUE TITLE
Block bug on Interacting

### ISSUE THREAD

**Issue by ssskkkyyy** [TuranicTeam/Altay#99]
#### Issue description
If I right click on some blocks, theres a really strange bug.
http://prntscr.com/jj5aut  <--- Screenshot

#### Steps to reproduce the issue
Right click on stained glass

#### OS and versions

* Altay: #63
* PHP: 7.2
* Server OS: Debian 8
* Game version: 1.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ZPlayzMCPE** [comment]
Hm, that's a little odd. Could be a block glitch? Client sides, or a MCPE server software issue. You'd need to ask someone about this, unless a fix is implemented.

**Comment by Epicrafter60** [comment]
It's also the same thing on PMMP, so don't worry. It's not really ruining the performance. But do you mean the items to have an interaction, if not, then there's a problem. I suggest maybe changing the item to something else in that case.

**Comment by ssskkkyyy** [comment]
@ZPlayZMCPE
This bug occurs no matter what item I'm using.

**Comment by EmreTr1** [comment]
Please try last commits and tell me about bug

**Comment by ssskkkyyy** [comment]
@EmreTr1 Now its fixed. Thanks!
